@LibrarySystem.Api_HostAddress = https://localhost:7008
@token = PASTE_LOGIN_TOKEN_HERE

### Register
POST {{LibrarySystem.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test123"
}


### Login
POST {{LibrarySystem.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test123"
}


### Get All Books
GET {{LibrarySystem.Api_HostAddress}}/api/books


### Create Book
POST {{LibrarySystem.Api_HostAddress}}/api/books
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Suç ve Ceza",
  "author": "Fyodor Dostoyevski",
  "stock": 3
}


### Delete Book
DELETE {{LibrarySystem.Api_HostAddress}}/api/books/2
Authorization: Bearer {{token}}


### Borrow Book
POST {{LibrarySystem.Api_HostAddress}}/api/borrow/2
Authorization: Bearer {{token}}


### My Books
GET {{LibrarySystem.Api_HostAddress}}/api/borrow/my-books
Authorization: Bearer {{token}}


### Return Book
POST {{LibrarySystem.Api_HostAddress}}/api/return/2
Authorization: Bearer {{token}}


### Borrow Without Token
POST {{LibrarySystem.Api_HostAddress}}/api/borrow/2


### Create Out Of Stock Book
POST {{LibrarySystem.Api_HostAddress}}/api/books
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Stok Test Kitabı",
  "author": "Test Yazar",
  "stock": 0
}


### Borrow Out Of Stock Book
POST {{LibrarySystem.Api_HostAddress}}/api/borrow/3
Authorization: Bearer {{token}}