@LibrarySystem.Api_HostAddress = https://localhost:7008

### Register
POST {{LibrarySystem.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test123"
}

### Login
POST {{LibrarySystem.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test123"
}